services:
  # 1. NƠI LƯU TRỮ (OBJECT STORAGE)
  minio:
    image: minio/minio
    container_name: minio
    networks:
      - debezium_default
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

  # Tự động tạo bucket 'warehouse' khi khởi động
  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 admin password) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb myminio/warehouse || true;
      exit 0;
      "

  # 2. THỦ THƯ (CATALOG MANAGEMENT)
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks:
      - debezium_default
    ports:
      - "19120:19120"

  # 3. BỘ MÁY XỬ LÝ (COMPUTE ENGINE - SPARK)
  spark:
    image: spark-iceberg-kafka:latest
    container_name: spark
    networks:
      - debezium_default
    depends_on:
      - minio
      - nessie
    ports:
      - "8888:8888" # Jupyter Lab
      - "8090:8080" # Spark UI
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    volumes:
      - ./notebooks:/home/iceberg/notebooks
      - ./spark-config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  # 4. TRUY VẤN TỐC ĐỘ CAO (QUERY ENGINE - TRINO)
  trino:
    image: trinodb/trino:latest
    container_name: trino
    networks:
      - debezium_default
    depends_on:
      - minio
      - nessie
    ports:
      - "8091:8080"
    environment:
      - AWS_REGION=us-east-1
    volumes:
      # Mount file cấu hình catalog riêng cho Trino
      - ./trino-config:/etc/trino/catalog

networks:
  debezium_default:
    external: true